resource_group_name     = "rg-terraform-web-sql-dbnew"
resource_group_location = "eastus2"
app_service_plan_name   = "appserviceplan-web-21-rkmnew"
app_service_name        = "terraform-web-021-rkmnew"
sql_server_name         = "terraform-sqlserver-021-rkmnew"
sql_database_name       = "ProductsDB-rkmnew"
sql_admin_login         = "userrkm01"
sql_admin_password      = "Test@123"
