resource_group_name     = "rg-terraform-web-sql-db"
resource_group_location = "westeurope"
app_service_plan_name   = "appserviceplan-web-21-rkm"
app_service_name        = "terraform-web-021-rkm"
sql_server_name         = "terraform-sqlserver-021-rkm"
sql_database_name       = "ProductsDB-rkm"
sql_admin_login         = "userrkm01"
sql_admin_password      = "Test@123"
